### ISSUE TITLE
Fixed subject exclamation and question marks

### ISSUE THREAD

**Issue by BitLiberal** [ATofighi/MyBB-Tags#47]
When I create a thread with question or exclamation in subject (-?, -!, -¿, -¡, useful for users with forums in Spanish, llike me) those characters are in the tag after.

Examples:
Are you serious? = The tag will be "serious?"
¿Que? = The tag will be "¿que?"
¡Eh! = The tag will be "¡Eh!"

I've solved by adding a line of code:

- Below this line:
```php
$subject = $thread['subject'];
```

- Add this other:
```php
$subject = str_replace(array("?", "¿", "!", "¡"), '', $subject);
```

**Comment by ATofighi** [comment]
#33
