### ISSUE TITLE
Url not found - Not solved

### ISSUE THREAD

**Issue by lArcade** [ATofighi/MyBB-Tags#51]
https://github.com/ATofighi/MyBB-Tags/issues/49#event-243957463
I have not solved it yet
What I have to do here?
https://github.com/ATofighi/MyBB-Tags/issues/33

**Comment by ATofighi** [comment]
you should ask your questions in community.mybb.com
you should insert this code to the `.htaccess` file:
https://github.com/ATofighi/MyBB-Tags/blob/master/tags-htaccess.txt

**Comment by lArcade** [comment]
Thanks :D
