### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by everton3x** [ATofighi/MyBB-Tags#57]
After activating the plugin, the following error occurs when accessing the forum:

> MyBB has experienced an internal SQL error and cannot continue.
> 
> SQL Error:
> 1055 - Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'fichamento.tags.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
> Query:
> SELECT SUM(threads.views) as sumviews, tags.name FROM `mybb_tags` tags LEFT JOIN `mybb_threads` threads on(tags.tid = threads.tid) LEFT JOIN `mybb_posts` posts on(threads.firstpost = posts.pid) WHERE (tags.name != '') AND threads.tid != '0' AND threads.visible = '1' AND threads.closed NOT LIKE 'moved|%' AND 1=1 group by tags.hash order by RAND() limit 0, 50

Disabling the plugin does not occur.

I'm using MyBB 1.8.8 with Mysql 5.7.16 on Ubuntu and Apache 2

**Comment by amadercode** [comment]
Me too get same error on my message boart with mybb 1.8.11 version as below

MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1055 - Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'admin_store_db.tags.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Query:
SELECT SUM(threads.views) as sumviews, tags.name FROM `TABLEPREFIX_tags` tags LEFT JOIN `TABLEPREFIX_threads` threads on(tags.tid = threads.tid) LEFT JOIN `TABLEPREFIX_posts` posts on(threads.firstpost = posts.pid) WHERE (tags.name != '') AND threads.tid != '0' AND threads.visible = '1' AND threads.closed NOT LIKE 'moved|%' AND 1=1 group by tags.hash order by RAND() limit 0, 50
Please contact the MyBB Group for technical support.
![mybb_error](https://cloud.githubusercontent.com/assets/22766572/24839821/4a975c1a-1d83-11e7-9cd9-285171c76adc.png)
