### ISSUE TITLE
Show tags on thread view

### ISSUE THREAD

**Issue by Cu8eeeR** [ATofighi/MyBB-Tags#58]

**Comment by ATofighi** [comment]
?

**Comment by ATofighi** [comment]
@Cu8eeeR Can you give me more details please?

**Comment by Cu8eeeR** [comment]
![threads](https://user-images.githubusercontent.com/778890/29248960-95136180-8025-11e7-8a55-d6069ce9fce8.png)

for example here: https://forum.warthunder.com/index.php?/forum/968-turnaje/
