### ISSUE TITLE
Tags (3.0.1) on MyBB	1.8.21

### ISSUE THREAD

**Issue by deejayses** [ATofighi/MyBB-Tags#77]
I, a installed this mod in a clean mybb.
Its fails and return a sql erro:
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1055 - Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column '_mybb2.tags.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Query:
SELECT * FROM `mybb_tags_slug` slugs LEFT JOIN `mybb_tags` tags on(tags.name = slugs.name) LEFT JOIN `mybb_threads` threads on(tags.tid = threads.tid) WHERE (1=1) AND threads.tid != '0' AND threads.visible = '1' AND threads.closed NOT LIKE 'moved|%' AND 1=1 group by slugs.slug order by RAND() limit 0, 50
Please contact the MyBB Group for technical support.

Can i resolv  this?
regards
working in [forum retro arcade](www.masqueconsolas.net)

**Comment by ATofighi** [comment]
A new version released: https://github.com/ATofighi/MyBB-Tags/releases/tag/3.0.3 This issue should fix in new version
