### ISSUE TITLE
Disable tags auto-filling from thread title

### ISSUE THREAD

**Issue by pleroma02** [ATofighi/MyBB-Tags#80]
Well maybe you need a reminder since this has been requested for years and it's still not an option but please add this option. The autofilled tags from the thread title render this absolutely useless. At least point me in the direction on how I can solve this myself I'd really like to actually use this plugin.

**Comment by ATofighi** [comment]
I guess that if you remove the following code from `tags_input` templace, you can achieve your request:
```
$('input[name=subject]').blur(function(){
	var txt = $(this).val();
	txt = $.trim(txt.replace(/([ +"'\\/\]\[,.-])/gi, ' '));
	var tags = txt.split(' ');
	var val = $('#tags').select2('val');
	for(var i in tags) {
		var tag = tags[i];
		val.push(tag);
	}
	var data = [];
	for(var i in val) {
		var tag = val[i];
		data.push({
			id: tag,
			text: tag
		});
	}
	$('#tags').select2('val', val);
	$('#tags').trigger('change');
});

```

**Comment by pleroma02** [comment]
Thank you, this seems to have worked!
